---
deployment:
  tasks:
    # Set the deployment path (modify 'webdepa1' to your cPanel username)
    - export DEPLOYPATH=/home/webdepa1/public_html/geojii

    # Clear the deployment directory
    - /bin/rm -rf $DEPLOYPATH/*

    # Install composer dependencies (make sure composer is available on the server)
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader --working-dir=$DEPLOYPATH

    # Copy all Laravel files and directories to the deployment path
    - /bin/cp -r * $DEPLOYPATH

    # Set appropriate permissions for Laravel
    - /bin/chmod -R 755 $DEPLOYPATH/storage

    # Create a symbolic link for the storage folder
    - /bin/ln -s /home/webdepa1/laravel_storage_path $DEPLOYPATH/storage/app/public

    # Generate the application key (if not already done)
    - /opt/cpanel/ea-php74/root/usr/bin/php $DEPLOYPATH/artisan key:generate

    # (Optional) Run database migrations and seeders (if needed)
    # - /opt/cpanel/ea-php74/root/usr/bin/php $DEPLOYPATH/artisan migrate --force
    # - /opt/cpanel/ea-php74/root/usr/bin/php $DEPLOYPATH/artisan db:seed --force

    # (Optional) Clear application cache and optimize
    # - /opt/cpanel/ea-php74/root/usr/bin/php $DEPLOYPATH/artisan optimize

    # (Optional) Set appropriate permissions for Laravel after migrations (if needed)
    # - /bin/chmod -R 755 $DEPLOYPATH/storage

    # (Optional) If you have a 'public' directory, copy its contents to the deployment path
    # - /bin/cp -r public/* $DEPLOYPATH

    # (Optional) If you have additional tasks after the deployment
    # - /usr/local/bin/php /path/to/your/extra_script.php
